host = "https://kyfw.12306.cn"
urls_dict = {
        "login":{
            "url":"/otn/resources/login.html",
            "referer":""},
        "uamtk":{
            "url":"/passport/web/auth/uamtk-static",
            "referer":""},
        "create_qr":{
            "url":"/passport/web/create-qr64",
            "referer":""
        },
        "check_qr":{
            "url":"/passport/web/checkqr",
            "referer":""
        },
        "user_login":{
            "url":"/otn/passport?redirect=/otn/login/userLogin",
            "referer":""
        },
        "uamauth_client":{
            "url":"/otn/uamauthclient",
            "referer":""
        },
        "uamtk_callback":{
            "url":"/passport/web/auth/uamtk?callback=jQuery191{}_{}",
            "referer":""
        },
        "check_user":{
            "url":"/otn/login/checkUser",
            "referer":""
        },
        "submit_order":{
            "url":"/otn/leftTicket/submitOrderRequest",
            "referer":""
        },
        "init_dc":{
            "url":"/otn/confirmPassenger/initDc",
            "referer":""
        },
        "get_passenger":{
            "url":"/otn/confirmPassenger/getPassengerDTOs",
            "referer":""
        },
        "check_order":{
            "url":"/otn/confirmPassenger/checkOrderInfo",
            "referer":""
        },
        "get_queue_count":{
            "url":"/otn/confirmPassenger/getQueueCount",
            "referer":""
        },
        "confirm_single":{
            "url":"/otn/confirmPassenger/confirmSingleForQueue",
            "referer":""
        },
        "query_order_wait_time":{
            "url":"/otn/confirmPassenger/queryOrderWaitTime?random={}&tourFlag=dc&_json_att=&REPEAT_SUBMIT_TOKEN={}",
            "referer":""
        },
        "result_order":{
            "url":"/otn/confirmPassenger/resultOrderForDcQueue",
            "referer":""
        },
        "pay_order":{
            "url":"/otn//payOrder/init?random={}",
            "referer":""
        }
    }
